// Writes src/lib/image/latinGlyphs.ts: the outlines of the Latin capitals,
// digits and punctuation the wallpaper uses, taken from the bundled Noto
// Sans Devanagari font (which also carries Noto Sans's Latin set; SIL Open
// Font License 1.1 -- see src/lib/image/fonts/NotoSansDevanagari-OFL.txt).
// Pre-extracted, like devanagariLabels.ts, so vectorFont.ts stays
// synchronous and also works in the browser.
// Run after changing the character set: npx tsx scripts/writeLatinGlyphs.ts
import fs from "node:fs";
import path from "node:path";

const CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789():-/+·.,'%&!?";

async function main() {
  const hb = await import("harfbuzzjs");
  const data = fs.readFileSync(path.join(process.cwd(), "src/lib/image/fonts/NotoSansDevanagari.ttf"));
  const face = new hb.Face(new hb.Blob(data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) as ArrayBuffer));
  const font = new hb.Font(face);

  const shape = (ch: string) => {
    const buffer = new hb.Buffer();
    buffer.addText(ch);
    buffer.guessSegmentProperties();
    hb.shape(font, buffer);
    return { glyph: buffer.getGlyphInfos()[0].codepoint, advance: buffer.getGlyphPositions()[0].xAdvance };
  };
  const numbers = (raw: string) => (raw.match(/-?\d*\.?\d+(?:e-?\d+)?/gi) ?? []).map(Number);

  // Cap height: the top of "H", so a glyph's em here is its cap height.
  const hPath = numbers(font.glyphToPath(shape("H").glyph));
  const capHeight = Math.max(...hPath.filter((_, i) => i % 2 === 1));
  const round = (n: number) => Math.round(n * 1000) / 1000;

  const entries = [...CHARS].map((ch) => {
    const { glyph, advance } = shape(ch);
    const tokens = font.glyphToPath(glyph).match(/[MLQCZ]|-?\d*\.?\d+(?:e-?\d+)?/gi) ?? [];
    let d = "";
    let pair: number[] = [];
    for (const token of tokens) {
      if (/^[MLQCZ]$/i.test(token)) {
        d += token;
        pair = [];
        continue;
      }
      pair.push(Number(token));
      if (pair.length === 2) {
        d += `${round(pair[0] / capHeight)} ${round((capHeight - pair[1]) / capHeight)} `;
        pair = [];
      }
    }
    d = d.trim().replace(/ ([MLQCZ])/g, "$1");
    return `  ${JSON.stringify(ch)}: { width: ${round(advance / capHeight)}, d: ${JSON.stringify(d)} },`;
  });

  const out = `// Generated by scripts/writeLatinGlyphs.ts -- do not edit by hand.
// Noto Sans Latin outlines (SIL Open Font License 1.1, see
// fonts/NotoSansDevanagari-OFL.txt), in cap-height units: x from the
// glyph's origin, y down from the cap top (cap top = 0, baseline = 1).

export interface LatinGlyph {
  /** Advance width, in cap heights. */
  width: number;
  /** Filled outline path. */
  d: string;
}

export const LATIN_GLYPHS: Record<string, LatinGlyph> = {
${entries.join("\n")}
};

/** Space advance, in cap heights. */
export const LATIN_SPACE_WIDTH = ${round(shape(" ").advance / capHeight)};
`;
  fs.writeFileSync(path.join(process.cwd(), "src/lib/image/latinGlyphs.ts"), out);
  console.log(`Wrote ${CHARS.length} glyphs (cap height ${capHeight} units)`);
}

main();
